name: flt_multilanguage
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+3
  get_it: ^3.0.3
  provider: ^3.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - locale/i18n_en.json
    - locale/i18n_vi.json

